module.exports = {

  '200' : [ 'may', 'OK'],
  '201' : [ 'may', 'Created' ],
  '202' : [ 'may', 'Accepted' ],
  '203' : [ 'may', 'Non-Authoritative Information' ],
  '204' : [ 'may', 'No Content' ],
  '205' : [ 'may', 'Reset Content' ],
  '206' : [ 'may', 'Partial Content' ],
  '207' : [ 'may', 'Multi-Status' ],
  '208' : [ 'may', 'Already Reported' ],
  '226' : [ 'may', 'IM Used' ],
  '300' : [ 'may', 'Multiple Choices' ],
  '301' : [ 'may', 'Moved Permanently' ],
  '302' : [ 'may', 'Found' ],
  '303' : [ 'may', 'See Other' ],
  '304' : [ 'may', 'Not Modified' ],
  '305' : [ 'may', 'Use Proxy' ],
  '306' : [ 'may', 'Switch Proxy' ],
  '307' : [ 'may', 'Temporary Redirect' ],
  '308' : [ 'may', 'Permanent Redirect' ],
  '400' : [ 'may not', 'Bad Request' ],
  '401' : [ 'may not', 'Unauthorized' ],
  '402' : [ 'may not', 'Payment Required' ],
  '403' : [ 'may not', 'Forbidden' ],
  '404' : [ 'cannot', 'Not Found' ],
  '405' : [ 'may not', 'Method Not Allowed' ],
  '406' : [ 'cannot', 'Not Acceptable' ],
  '407' : [ 'may not', 'Proxy Authentication Required' ],
  '408' : [ 'cannot', 'Request Timeout' ],
  '409' : [ 'may not', 'Conflict' ],
  '410' : [ 'cannot', 'Gone' ],

};